[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "droid"
authors = [
    {name = "Alexander Khazatsky "}
]
description = "Distributed Robot Interaction Dataset"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["robotics"]
dependencies = [
    "boto3",
    "customtkinter",
    "dm-control==1.0.5",
    "gym",
    "h5py",
    "imageio>=2.31.2",
    "imageio-ffmpeg>=0.5.1",
    "matplotlib",
    "mujoco",
    "open3d",
    "opencv-contrib-python>=4.11.0.86",
    "Pillow",
    "protobuf==3.20.1",
    "psutil",
    "pyrallis",
    "scipy",
    "tqdm",
    "tyro>=0.9.1",
    "zerorpc",
    "lerobot",
]

[tool.uv.sources]
lerobot = { git = "https://github.com/huggingface/lerobot", rev = "0cf864870cf29f4738d3ade893e6fd13fbd7cdb5" }

[project.optional-dependencies]
dev = [
    "black[jupyter]",
    "ipython",
    "pre-commit",
    "ruff",
]
postprocessing = [
    "scikit-image",
]

[project.urls]
homepage = "https://github.com/droid-dataset/droid"
repository = "https://github.com/droid-dataset/droid"
documentation = "https://github.com/droid-dataset/droid"

[tool.black]
line-length = 121
target-version = ["py37", "py38", "py39", "py310"]
preview = true

[tool.ruff]
line-length = 121
target-version = "py38"
select = ["A", "B", "C90", "E", "F", "I", "RUF", "W"]
ignore = ["F405", "B006", "C901", "F403", "E722"]
[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[tool.isort]
profile = "black"
line_length = 121
skip = ["__init__.py"]
filter_files = true
py_version = "all"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["cache"]
